import type { Locale } from './product';
import type { Avatar } from './room-flow';

export type PlayerShellUiCopy = {
  player:string; guest:string; progress:[string,string,string,string,string,string]; joinQuickly:string; join:string; joinHelp:string; roomCode:string; normalized:string; checkingRoom:string; continue:string;
  personalUi:string; language:string; languageHelp:string; back:string; identity:string; avatar:string; nickname:string; categoryLabels:Record<Avatar['category'],string>; nicknameHelp:string; avatarPolicy:string; joining:string;
  waiting:string; waitingDetail:string; joinedAs:string; players:string; ready:string; gamePreview:string; spectatorNotice:string; updating:string;
  paused:string; live:string; rules:string; waitingHost:string; roundInProgress:string; release11:string; authorityNotice:string;
  results:string; roundComplete:(nickname:string)=>string; privatePlacement:string; pending:string; stayInRoom:string; leaveRoom:string;
  supabaseMissing:string; refreshFailed:string; realtimeFailed:string; hostEnded:string; continueFailed:string; joinFailed:string; readyFailed:string;
};

const en: PlayerShellUiCopy = {
  player:'Player',guest:'Guest · no visible account required',progress:['Join','Language','Identity','Lobby','Play','Result'],joinQuickly:'Join quickly',join:'Join Room',joinHelp:'Enter the room code from the Host, scan the room QR code, or open the room link. A saved seat on this device is recovered automatically where possible.',roomCode:'Room code',normalized:'Normalized',checkingRoom:'Checking room…',continue:'Continue',personalUi:'Personal UI',language:'Language',languageHelp:'Your interface language is personal. It does not change the room/game content language for everyone else.',back:'Back',identity:'Your identity',avatar:'Avatar',nickname:'Nickname',categoryLabels:{'chinese-zodiac':'Chinese zodiac','western-zodiac':'Western zodiac',animals:'Animals',vegetables:'Vegetables',fruits:'Fruits'},nicknameHelp:'Generated from the selected built-in avatar. The server applies room moderation rules when you join.',avatarPolicy:'Release 1 uses built-in avatars only. Custom participant photos are unavailable.',joining:'Joining…',waiting:'Waiting for Host',waitingDetail:'You are in the room. The game starts when the Host is ready.',joinedAs:'Joined as',players:'Players',ready:'Ready',gamePreview:'Game preview',spectatorNotice:'You joined as a spectator. In Quick Draw, spectators may still guess when audience guessing is enabled, but they do not enter the current artist rotation.',updating:'Updating…',paused:'PAUSED',live:'LIVE',rules:'Rules',waitingHost:'Waiting for Host.',roundInProgress:'Round in progress.',release11:'This game is scheduled for Release 1.1.',authorityNotice:'Accepted answers, scores, ties, and rankings are always determined by the authoritative server, never by this browser.',results:'Results',roundComplete:(nickname)=>`Round complete, ${nickname}.`,privatePlacement:'Your private placement',pending:'Pending',stayInRoom:'Stay in the room. When the Host chooses Replay or Change Game, this screen automatically returns to the lobby.',leaveRoom:'Leave room',supabaseMissing:'The Supabase connection has not been configured yet.',refreshFailed:'Could not refresh room state.',realtimeFailed:'Realtime connection failed.',hostEnded:'The Host ended this room.',continueFailed:'Could not continue.',joinFailed:'Could not join room.',readyFailed:'Could not update Ready state.'
};

export const PLAYER_SHELL_UI_COPY: Record<Locale, PlayerShellUiCopy> = {
  en,
  'zh-Hant':{...en,player:'玩家',guest:'訪客 · 不需建立可見帳號',progress:['加入','語言','身分','大廳','遊戲','結果'],joinQuickly:'快速加入',join:'加入房間',joinHelp:'輸入主持人提供的房間代碼、掃描房間 QR 碼，或開啟房間連結。若此裝置已有保存的席位，系統會在可行時自動恢復。',roomCode:'房間代碼',normalized:'標準化代碼',checkingRoom:'正在檢查房間…',continue:'繼續',personalUi:'個人介面',language:'語言',languageHelp:'你的介面語言只影響你自己，不會改變所有人的房間／遊戲內容語言。',back:'返回',identity:'你的身分',avatar:'頭像',nickname:'暱稱',categoryLabels:{'chinese-zodiac':'十二生肖','western-zodiac':'西洋星座',animals:'動物',vegetables:'蔬菜',fruits:'水果'},nicknameHelp:'暱稱由所選內建頭像產生。加入時伺服器會套用房間的暱稱管理規則。',avatarPolicy:'Release 1 僅使用內建頭像，不提供自訂參與者照片。',joining:'加入中…',waiting:'等待主持人',waitingDetail:'你已加入房間。主持人準備好後遊戲就會開始。',joinedAs:'加入名稱',players:'玩家',ready:'準備完成',gamePreview:'遊戲預覽',spectatorNotice:'你以觀眾身分加入。Quick Draw 若開啟觀眾猜答，你仍可猜答案，但不會加入目前的畫家順序。',updating:'更新中…',paused:'已暫停',live:'進行中',rules:'規則',waitingHost:'等待主持人。',roundInProgress:'回合進行中。',release11:'此遊戲預定於 Release 1.1 推出。',authorityNotice:'接受的答案、分數、並列與排名一律由權威伺服器決定，不由此瀏覽器決定。',results:'結果',roundComplete:(nickname)=>`回合完成，${nickname}。`,privatePlacement:'你的私人名次',pending:'待定',stayInRoom:'請留在房間內。主持人選擇「再玩一次」或「換遊戲」後，此畫面會自動返回大廳。',leaveRoom:'離開房間',supabaseMissing:'尚未設定 Supabase 連線。',refreshFailed:'無法更新房間狀態。',realtimeFailed:'即時連線失敗。',hostEnded:'主持人已結束此房間。',continueFailed:'無法繼續。',joinFailed:'無法加入房間。',readyFailed:'無法更新準備狀態。'},
  'zh-Hans':{...en,player:'玩家',guest:'访客 · 无需创建可见账号',progress:['加入','语言','身份','大厅','游戏','结果'],joinQuickly:'快速加入',join:'加入房间',joinHelp:'输入主持人提供的房间代码、扫描房间 QR 码，或打开房间链接。如果此设备已有保存的席位，系统会在可行时自动恢复。',roomCode:'房间代码',normalized:'标准化代码',checkingRoom:'正在检查房间…',continue:'继续',personalUi:'个人界面',language:'语言',languageHelp:'你的界面语言只影响你自己，不会改变所有人的房间／游戏内容语言。',back:'返回',identity:'你的身份',avatar:'头像',nickname:'昵称',categoryLabels:{'chinese-zodiac':'十二生肖','western-zodiac':'西方星座',animals:'动物',vegetables:'蔬菜',fruits:'水果'},nicknameHelp:'昵称由所选内置头像生成。加入时服务器会应用房间昵称管理规则。',avatarPolicy:'Release 1 仅使用内置头像，不提供自定义参与者照片。',joining:'加入中…',waiting:'等待主持人',waitingDetail:'你已加入房间。主持人准备好后游戏就会开始。',joinedAs:'加入名称',players:'玩家',ready:'准备完成',gamePreview:'游戏预览',spectatorNotice:'你以观众身份加入。Quick Draw 如果开启观众猜答，你仍可猜答案，但不会进入当前画家顺序。',updating:'更新中…',paused:'已暂停',live:'进行中',rules:'规则',waitingHost:'等待主持人。',roundInProgress:'回合进行中。',release11:'此游戏计划在 Release 1.1 推出。',authorityNotice:'接受的答案、分数、并列和排名一律由权威服务器决定，不由此浏览器决定。',results:'结果',roundComplete:(nickname)=>`回合完成，${nickname}。`,privatePlacement:'你的私人名次',pending:'待定',stayInRoom:'请留在房间内。主持人选择“再玩一次”或“换游戏”后，此页面会自动返回大厅。',leaveRoom:'离开房间',supabaseMissing:'尚未配置 Supabase 连接。',refreshFailed:'无法刷新房间状态。',realtimeFailed:'实时连接失败。',hostEnded:'主持人已结束此房间。',continueFailed:'无法继续。',joinFailed:'无法加入房间。',readyFailed:'无法更新准备状态。'},
  es:{...en,player:'Jugador',guest:'Invitado · no requiere cuenta visible',progress:['Unirse','Idioma','Identidad','Sala','Jugar','Resultado'],joinQuickly:'Únete rápido',join:'Unirse a sala',joinHelp:'Introduce el código del anfitrión, escanea el QR de la sala o abre el enlace. Cuando es posible, un asiento guardado en este dispositivo se recupera automáticamente.',roomCode:'Código de sala',normalized:'Código normalizado',checkingRoom:'Comprobando sala…',continue:'Continuar',personalUi:'Interfaz personal',language:'Idioma',languageHelp:'Tu idioma de interfaz es personal. No cambia el idioma del contenido de sala/juego para los demás.',back:'Atrás',identity:'Tu identidad',avatar:'Avatar',nickname:'Apodo',categoryLabels:{'chinese-zodiac':'Zodiaco chino','western-zodiac':'Zodiaco occidental',animals:'Animales',vegetables:'Verduras',fruits:'Frutas'},nicknameHelp:'Se genera a partir del avatar integrado elegido. El servidor aplica las reglas de moderación de la sala al entrar.',avatarPolicy:'Release 1 usa solamente avatares integrados. No se permiten fotos personalizadas de participantes.',joining:'Entrando…',waiting:'Esperando al anfitrión',waitingDetail:'Ya estás en la sala. El juego comienza cuando el anfitrión esté listo.',joinedAs:'Te uniste como',players:'Jugadores',ready:'Listo',gamePreview:'Vista previa',spectatorNotice:'Entraste como espectador. En Quick Draw todavía puedes adivinar si el anfitrión permite respuestas del público, pero no entras en la rotación actual de artistas.',updating:'Actualizando…',paused:'PAUSADO',live:'EN VIVO',rules:'Reglas',waitingHost:'Esperando al anfitrión.',roundInProgress:'Ronda en curso.',release11:'Este juego está programado para Release 1.1.',authorityNotice:'Las respuestas aceptadas, puntuaciones, empates y clasificaciones siempre las decide el servidor autoritativo, nunca este navegador.',results:'Resultados',roundComplete:(nickname)=>`Ronda completada, ${nickname}.`,privatePlacement:'Tu posición privada',pending:'Pendiente',stayInRoom:'Permanece en la sala. Cuando el anfitrión elija Repetir o Cambiar juego, esta pantalla volverá automáticamente a la sala.',leaveRoom:'Salir de la sala',supabaseMissing:'La conexión de Supabase aún no está configurada.',refreshFailed:'No se pudo actualizar el estado de la sala.',realtimeFailed:'Falló la conexión en tiempo real.',hostEnded:'El anfitrión cerró esta sala.',continueFailed:'No se pudo continuar.',joinFailed:'No se pudo entrar a la sala.',readyFailed:'No se pudo actualizar el estado Listo.'},
  ja:{...en,player:'プレイヤー',guest:'ゲスト · 見えるアカウントは不要',progress:['参加','言語','アイデンティティ','ロビー','プレイ','結果'],joinQuickly:'すぐ参加',join:'ルームに参加',joinHelp:'ホストのルームコードを入力するか、QRを読み取るか、ルームリンクを開きます。この端末に保存された席があれば、可能な場合は自動復旧します。',roomCode:'ルームコード',normalized:'標準化コード',checkingRoom:'ルームを確認中…',continue:'続ける',personalUi:'個人インターフェース',language:'言語',languageHelp:'インターフェース言語は個人設定です。他の人の共有ルーム／ゲーム内容言語は変わりません。',back:'戻る',identity:'あなたのアイデンティティ',avatar:'アバター',nickname:'ニックネーム',categoryLabels:{'chinese-zodiac':'十二支','western-zodiac':'西洋星座',animals:'動物',vegetables:'野菜',fruits:'果物'},nicknameHelp:'選択した内蔵アバターから生成されます。参加時にサーバーがルームのニックネーム管理ルールを適用します。',avatarPolicy:'Release 1 は内蔵アバターのみ使用します。参加者のカスタム写真は利用できません。',joining:'参加中…',waiting:'ホストを待っています',waitingDetail:'ルームに参加しました。ホストの準備ができるとゲームが始まります。',joinedAs:'参加名',players:'プレイヤー',ready:'準備完了',gamePreview:'ゲームプレビュー',spectatorNotice:'観客として参加しました。Quick Draw で観客回答が有効なら回答できますが、現在の描く人の順番には入りません。',updating:'更新中…',paused:'一時停止',live:'ライブ',rules:'ルール',waitingHost:'ホストを待っています。',roundInProgress:'ラウンド進行中。',release11:'このゲームは Release 1.1 で提供予定です。',authorityNotice:'正解判定、得点、同点、順位は常に権威サーバーが決定し、このブラウザでは決定しません。',results:'結果',roundComplete:(nickname)=>`ラウンド完了、${nickname}。`,privatePlacement:'あなたの個人順位',pending:'保留中',stayInRoom:'ルームに残ってください。ホストが「もう一度」または「ゲーム変更」を選ぶと自動的にロビーへ戻ります。',leaveRoom:'ルームを退出',supabaseMissing:'Supabase 接続がまだ設定されていません。',refreshFailed:'ルーム状態を更新できませんでした。',realtimeFailed:'リアルタイム接続に失敗しました。',hostEnded:'ホストがこのルームを終了しました。',continueFailed:'続行できませんでした。',joinFailed:'ルームに参加できませんでした。',readyFailed:'準備状態を更新できませんでした。'},
  ko:{...en,player:'플레이어',guest:'게스트 · 보이는 계정 필요 없음',progress:['참가','언어','아이덴티티','로비','플레이','결과'],joinQuickly:'빠르게 참가',join:'방 참가',joinHelp:'호스트의 방 코드를 입력하거나 QR을 스캔하거나 방 링크를 여세요. 이 기기에 저장된 좌석이 있으면 가능한 경우 자동으로 복구합니다.',roomCode:'방 코드',normalized:'정규화 코드',checkingRoom:'방 확인 중…',continue:'계속',personalUi:'개인 인터페이스',language:'언어',languageHelp:'인터페이스 언어는 개인 설정입니다. 다른 사람의 공유 방/게임 콘텐츠 언어는 바뀌지 않습니다.',back:'뒤로',identity:'내 아이덴티티',avatar:'아바타',nickname:'닉네임',categoryLabels:{'chinese-zodiac':'십이지','western-zodiac':'서양 별자리',animals:'동물',vegetables:'채소',fruits:'과일'},nicknameHelp:'선택한 내장 아바타에서 생성됩니다. 참가 시 서버가 방의 닉네임 관리 규칙을 적용합니다.',avatarPolicy:'Release 1은 내장 아바타만 사용합니다. 참가자 사용자 지정 사진은 사용할 수 없습니다.',joining:'참가 중…',waiting:'호스트를 기다리는 중',waitingDetail:'방에 참가했습니다. 호스트가 준비되면 게임이 시작됩니다.',joinedAs:'참가 이름',players:'플레이어',ready:'준비 완료',gamePreview:'게임 미리보기',spectatorNotice:'관전자로 참가했습니다. Quick Draw에서 관전자 추측이 허용되면 답을 맞힐 수 있지만 현재 아티스트 순서에는 들어가지 않습니다.',updating:'업데이트 중…',paused:'일시정지',live:'라이브',rules:'규칙',waitingHost:'호스트를 기다리는 중입니다.',roundInProgress:'라운드 진행 중입니다.',release11:'이 게임은 Release 1.1에 제공될 예정입니다.',authorityNotice:'정답 판정, 점수, 동점, 순위는 항상 권위 서버가 결정하며 이 브라우저가 결정하지 않습니다.',results:'결과',roundComplete:(nickname)=>`라운드 완료, ${nickname}.`,privatePlacement:'내 개인 순위',pending:'대기 중',stayInRoom:'방에 남아 있으세요. 호스트가 다시 하기 또는 게임 변경을 선택하면 이 화면이 자동으로 로비로 돌아갑니다.',leaveRoom:'방 나가기',supabaseMissing:'Supabase 연결이 아직 설정되지 않았습니다.',refreshFailed:'방 상태를 새로고칠 수 없습니다.',realtimeFailed:'실시간 연결에 실패했습니다.',hostEnded:'호스트가 이 방을 종료했습니다.',continueFailed:'계속할 수 없습니다.',joinFailed:'방에 참가할 수 없습니다.',readyFailed:'준비 상태를 업데이트할 수 없습니다.'}
};
