import type { Locale } from './product';

export type ShellUiCopy = {
  joinRoom:string; hostGame:string; interfaceLanguage:string; tagline:string; hero:string; intro:string; joinCode:string;
  timeFirst:string; timeHelp:string; availableTime:string; min:string; gameLibrary:string; gamesFit:(m:number)=>string; releaseNote:string;
  minPlayers:string; noGameMaximum:string; best:string; screen:string; hostTitle:string; hostSubtitle:string; hostBody:string; openHost:string;
  playerTitle:string; playerSubtitle:string; playerBody:string; openPlayer:string; footer:string;
};

const en: ShellUiCopy = {
  joinRoom:'Join Room',hostGame:'Host a Game',interfaceLanguage:'Interface language',tagline:'Short games · real connections',hero:'Make every spare moment playable.',intro:'Choose how much time your group has, open a room, and launch a ready-made multiplayer game. Participants join from their phones without creating a visible account.',joinCode:'Join With Code',timeFirst:'Time-first setup',timeHelp:'Choose 3, 5, 8, or 10 minutes first. Game settings and readiness adapt to the available time and group size.',availableTime:'Available time',min:'min',gameLibrary:'Release 1 game library',gamesFit:(m)=>`Games that fit ${m} minutes`,releaseNote:'Release 1 · three production games',minPlayers:'Min',noGameMaximum:'No game-rule maximum',best:'Best',screen:'Screen',hostTitle:'TimeFillerGames Host',hostSubtitle:'Confident control',hostBody:'Choose time, filter the game shelf, configure rules, open the room, verify readiness, run the game, and review results.',openHost:'Open Host flow →',playerTitle:'TimeFillerGames Player',playerSubtitle:'Immediate participation',playerBody:'Join by PIN, QR, or link, choose language, avatar and nickname, wait in the lobby, play, and see results.',openPlayer:'Open Player flow →',footer:'Make every spare moment playable.'
};

export const SHELL_UI_COPY: Record<Locale, ShellUiCopy> = {
  en,
  'zh-Hant':{...en,joinRoom:'加入房間',hostGame:'主持遊戲',interfaceLanguage:'介面語言',tagline:'短遊戲 · 真連結',hero:'讓每一段空檔都能開始玩。',intro:'先選擇團體有多少時間，再開啟房間並啟動現成的多人遊戲。參與者可直接用手機加入，不需建立可見帳號。',joinCode:'使用代碼加入',timeFirst:'時間優先設定',timeHelp:'先選 3、5、8 或 10 分鐘。遊戲設定與準備狀態會依可用時間與團體人數調整。',availableTime:'可用時間',min:'分',gameLibrary:'Release 1 遊戲庫',gamesFit:(m)=>`適合 ${m} 分鐘的遊戲`,releaseNote:'Release 1 · 三款正式遊戲',minPlayers:'最低',noGameMaximum:'遊戲規則無上限',best:'建議',screen:'螢幕',hostTitle:'TimeFillerGames 主持端',hostSubtitle:'清楚掌控',hostBody:'選時間、篩選遊戲、設定規則、開房、確認準備、進行遊戲並查看結果。',openHost:'開啟主持流程 →',playerTitle:'TimeFillerGames 玩家端',playerSubtitle:'立即參與',playerBody:'用 PIN、QR 或連結加入，選擇語言、頭像與暱稱，進入大廳後直接遊玩並查看結果。',openPlayer:'開啟玩家流程 →',footer:'讓每一段空檔都能開始玩。'},
  'zh-Hans':{...en,joinRoom:'加入房间',hostGame:'主持游戏',interfaceLanguage:'界面语言',tagline:'短游戏 · 真连接',hero:'让每一段空档都能开始玩。',intro:'先选择团队有多少时间，再开启房间并启动现成的多人游戏。参与者可直接用手机加入，无需创建可见账号。',joinCode:'使用代码加入',timeFirst:'时间优先设置',timeHelp:'先选 3、5、8 或 10 分钟。游戏设置与准备状态会根据可用时间和团队人数调整。',availableTime:'可用时间',min:'分',gameLibrary:'Release 1 游戏库',gamesFit:(m)=>`适合 ${m} 分钟的游戏`,releaseNote:'Release 1 · 三款正式游戏',minPlayers:'最低',noGameMaximum:'游戏规则无上限',best:'建议',screen:'屏幕',hostTitle:'TimeFillerGames 主持端',hostSubtitle:'清楚掌控',hostBody:'选时间、筛选游戏、设置规则、开房、确认准备、运行游戏并查看结果。',openHost:'开启主持流程 →',playerTitle:'TimeFillerGames 玩家端',playerSubtitle:'立即参与',playerBody:'用 PIN、QR 或链接加入，选择语言、头像和昵称，进入大厅后直接游戏并查看结果。',openPlayer:'开启玩家流程 →',footer:'让每一段空档都能开始玩。'},
  es:{...en,joinRoom:'Unirse a sala',hostGame:'Organizar juego',interfaceLanguage:'Idioma de la interfaz',tagline:'Juegos cortos · conexiones reales',hero:'Haz jugable cada momento libre.',intro:'Elige cuánto tiempo tiene el grupo, abre una sala e inicia un juego multijugador listo para usar. Los participantes entran desde el teléfono sin crear una cuenta visible.',joinCode:'Unirse con código',timeFirst:'Configuración según el tiempo',timeHelp:'Elige primero 3, 5, 8 o 10 minutos. La configuración y la preparación se adaptan al tiempo disponible y al tamaño del grupo.',availableTime:'Tiempo disponible',min:'min',gameLibrary:'Biblioteca Release 1',gamesFit:(m)=>`Juegos para ${m} minutos`,releaseNote:'Release 1 · tres juegos de producción',minPlayers:'Mín.',noGameMaximum:'Sin máximo por regla',best:'Ideal',screen:'Pantalla',hostTitle:'TimeFillerGames Host',hostSubtitle:'Control claro',hostBody:'Elige tiempo, filtra juegos, configura reglas, abre la sala, verifica la preparación, dirige el juego y revisa los resultados.',openHost:'Abrir flujo de anfitrión →',playerTitle:'TimeFillerGames Player',playerSubtitle:'Participación inmediata',playerBody:'Entra por PIN, QR o enlace, elige idioma, avatar y apodo, espera en la sala, juega y consulta los resultados.',openPlayer:'Abrir flujo de jugador →',footer:'Haz jugable cada momento libre.'},
  ja:{...en,joinRoom:'ルームに参加',hostGame:'ゲームを主催',interfaceLanguage:'インターフェース言語',tagline:'短いゲーム · 本当のつながり',hero:'すきま時間を、すぐ遊べる時間に。',intro:'グループの空き時間を選び、ルームを開いて、用意済みのマルチプレイヤーゲームを開始します。参加者は見えるアカウントを作らずスマホから参加できます。',joinCode:'コードで参加',timeFirst:'時間優先設定',timeHelp:'まず3、5、8、10分から選びます。設定と準備状態は利用時間と人数に合わせて調整されます。',availableTime:'利用できる時間',min:'分',gameLibrary:'Release 1 ゲームライブラリ',gamesFit:(m)=>`${m}分に合うゲーム`,releaseNote:'Release 1 · 正式3ゲーム',minPlayers:'最低',noGameMaximum:'ゲームルール上の上限なし',best:'推奨',screen:'画面',hostTitle:'TimeFillerGames Host',hostSubtitle:'明確なコントロール',hostBody:'時間を選び、ゲームを絞り、ルールを設定し、ルームを開き、準備を確認してゲームを進行し結果を確認します。',openHost:'ホスト画面を開く →',playerTitle:'TimeFillerGames Player',playerSubtitle:'すぐ参加',playerBody:'PIN、QR、リンクで参加し、言語・アバター・ニックネームを選び、ロビーからプレイして結果を確認します。',openPlayer:'プレイヤー画面を開く →',footer:'すきま時間を、すぐ遊べる時間に。'},
  ko:{...en,joinRoom:'방 참가',hostGame:'게임 호스트',interfaceLanguage:'인터페이스 언어',tagline:'짧은 게임 · 진짜 연결',hero:'모든 빈 시간을 플레이 시간으로.',intro:'그룹에 남은 시간을 고르고 방을 연 뒤 준비된 멀티플레이 게임을 시작하세요. 참가자는 보이는 계정을 만들지 않고 휴대폰으로 참여합니다.',joinCode:'코드로 참가',timeFirst:'시간 우선 설정',timeHelp:'먼저 3, 5, 8, 10분 중 선택합니다. 게임 설정과 준비 상태가 시간과 그룹 크기에 맞춰집니다.',availableTime:'사용 가능한 시간',min:'분',gameLibrary:'Release 1 게임 라이브러리',gamesFit:(m)=>`${m}분에 맞는 게임`,releaseNote:'Release 1 · 정식 게임 3개',minPlayers:'최소',noGameMaximum:'게임 규칙상 최대 없음',best:'권장',screen:'화면',hostTitle:'TimeFillerGames Host',hostSubtitle:'명확한 제어',hostBody:'시간을 선택하고 게임을 고른 뒤 규칙을 설정하고 방을 열어 준비 상태를 확인하고 게임을 진행한 후 결과를 검토합니다.',openHost:'호스트 흐름 열기 →',playerTitle:'TimeFillerGames Player',playerSubtitle:'즉시 참여',playerBody:'PIN, QR 또는 링크로 참가하고 언어, 아바타, 닉네임을 선택한 뒤 로비에서 게임을 시작하고 결과를 확인합니다.',openPlayer:'플레이어 흐름 열기 →',footer:'모든 빈 시간을 플레이 시간으로.'}
};
